version: '3'

services:

  front:
    build: ../../part1/1.10/
    ports:
      - 5000:5000

  back:
    build: ../../part1/1.11/
    environment:
      - REDIS=redis
    ports:
      - 8000:8000

  redis:
    image: redis:latest