version: '3'

services:

  front:
    build: ../../part1/1.10/
    ports:
      - 5000:5000

  back:
    build: ../../part1/1.11/
    depends_on:
      - db
    environment:
      - REDIS=redis
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=test_db
      - DB_HOST=db
    ports:
      - 8000:8000

  redis:
    image: redis:latest

  db:
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=test_db
    image: postgres:latest
    restart: unless-stopped

  nginx:
    depends_on:
      - front
      - back
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf