version: '3.5'

services:

  front:
    build: frontend/
    ports:
      - 3000:3000

  back:
    build: backend/
    ports:
      - 5000:5000
    volumes:
      - models:/src/model

  training:
    build: training/
    volumes:
      - ./imgs:/imgs
      - ./data:/data
      - models:/model

volumes:
  models: